### ISSUE TITLE
Change local git config

### ISSUE THREAD

**Issue by Paul2708** [CoolePizza/Bingo#1]
Hey, at the moment you commit changes using "BuildTools" as author.
You can change it by using the following with your name and GitHub email address.
```
$ git config --global user.name "John Doe"
$ git config --global user.email johndoe@example.com
```
*Source: [Git Wiki](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration)*

Greetings, Paul.

**Comment by booky10** [comment]
I think it is "BuildTools" because of the BuildTools from spigot, they are changing the git config name and email address.
